import { sql } from 'drizzle-orm';
import { integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { uuidv7 } from 'uuidv7';

/**
 * All `id` columns are UUIDv7 (time-sortable) generated by the app on insert, so
 * list endpoints can use the id directly as a pagination cursor (see architecture §4/§6).
 */
const primaryId = () =>
  text('id')
    .primaryKey()
    .$defaultFn(() => uuidv7());

const isoNow = () => new Date().toISOString();

export const users = sqliteTable('users', {
  id: primaryId(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  username: text('username').notNull(),
  language: text('language').notNull().default('en'),
  theme: text('theme').notNull().default('light'),
  dailyGoal: integer('daily_goal').notNull().default(20),
  createdAt: text('created_at').notNull().$defaultFn(isoNow),
  updatedAt: text('updated_at').notNull().$defaultFn(isoNow),
});

export const subjects = sqliteTable('subjects', {
  id: primaryId(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  description: text('description'),
  color: text('color'),
  icon: text('icon'),
  createdAt: text('created_at').notNull().$defaultFn(isoNow),
  updatedAt: text('updated_at').notNull().$defaultFn(isoNow),
});

export const cards = sqliteTable('cards', {
  id: primaryId(),
  subjectId: text('subject_id')
    .notNull()
    .references(() => subjects.id, { onDelete: 'cascade' }),
  question: text('question').notNull(),
  answer: text('answer').notNull(),
  hints: text('hints', { mode: 'json' }).$type<string[]>().notNull().default(sql`'[]'`),
  tags: text('tags', { mode: 'json' }).$type<string[]>().notNull().default(sql`'[]'`),
  createdAt: text('created_at').notNull().$defaultFn(isoNow),
  updatedAt: text('updated_at').notNull().$defaultFn(isoNow),
});

export const cardProgress = sqliteTable(
  'card_progress',
  {
    id: primaryId(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    cardId: text('card_id')
      .notNull()
      .references(() => cards.id, { onDelete: 'cascade' }),
    interval: integer('interval').notNull().default(1),
    easeFactor: real('ease_factor').notNull().default(2.5),
    repetitions: integer('repetitions').notNull().default(0),
    nextReviewDate: text('next_review_date').notNull(),
    lastReviewDate: text('last_review_date'),
    status: text('status', {
      enum: ['new', 'learning', 'reviewing', 'mastered'],
    })
      .notNull()
      .default('new'),
    createdAt: text('created_at').notNull().$defaultFn(isoNow),
    updatedAt: text('updated_at').notNull().$defaultFn(isoNow),
  },
  (table) => [uniqueIndex('card_progress_user_card_unique').on(table.userId, table.cardId)]
);

export const reviewHistory = sqliteTable('review_history', {
  id: primaryId(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  cardId: text('card_id')
    .notNull()
    .references(() => cards.id, { onDelete: 'cascade' }),
  subjectId: text('subject_id')
    .notNull()
    .references(() => subjects.id, { onDelete: 'cascade' }),
  quality: integer('quality').notNull(),
  reviewedAt: text('reviewed_at').notNull().$defaultFn(isoNow),
  timeSpent: integer('time_spent').notNull(),
  wasHintUsed: integer('was_hint_used', { mode: 'boolean' }).notNull().default(false),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Subject = typeof subjects.$inferSelect;
export type NewSubject = typeof subjects.$inferInsert;
export type Card = typeof cards.$inferSelect;
export type NewCard = typeof cards.$inferInsert;
export type CardProgress = typeof cardProgress.$inferSelect;
export type NewCardProgress = typeof cardProgress.$inferInsert;
export type ReviewHistory = typeof reviewHistory.$inferSelect;
export type NewReviewHistory = typeof reviewHistory.$inferInsert;
