import { sql } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { uuidv7 } from 'uuidv7';

/**
 * All `id` columns are UUIDv7 (time-sortable) generated by the app on insert, so
 * list endpoints can use the id directly as a pagination cursor (see architecture §4/§6).
 * Timestamps are stored as ISO 8601 text so they sort chronologically and compare directly.
 */
const primaryId = () =>
  text('id')
    .primaryKey()
    .$defaultFn(() => uuidv7());

const isoNow = () => new Date().toISOString();

export const users = pgTable('users', {
  id: primaryId(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  username: text('username').notNull(),
  language: text('language').notNull().default('en'),
  theme: text('theme').notNull().default('light'),
  dailyGoal: integer('daily_goal').notNull().default(20),
  createdAt: text('created_at').notNull().$defaultFn(isoNow),
  updatedAt: text('updated_at').notNull().$defaultFn(isoNow),
});

/** Content language a card is authored in. Defaults to English. */
export const CARD_LANGUAGES = ['en', 'pt'] as const;
export type CardLanguage = (typeof CARD_LANGUAGES)[number];

export const subjects = pgTable(
  'subjects',
  {
    id: primaryId(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    description: text('description'),
    color: text('color'),
    icon: text('icon'),
    // Public (catalog) subjects are owned by the system user and visible to everyone.
    isPublic: boolean('is_public').notNull().default(false),
    createdAt: text('created_at').notNull().$defaultFn(isoNow),
    updatedAt: text('updated_at').notNull().$defaultFn(isoNow),
  },
  (table) => [
    index('subjects_user_idx').on(table.userId),
    index('subjects_public_idx').on(table.isPublic),
  ]
);

/** Card kinds: `open` is Markdown Q&A; the rest are auto-graded by the server. */
export const CARD_TYPES = ['open', 'quiz', 'type-answer', 'match'] as const;
export type CardType = (typeof CARD_TYPES)[number];

/** A single multiple-choice option (quiz). `isCorrect` is server-only — stripped before study. */
export type CardChoice = { id: string; text: string; isCorrect: boolean };
/** A left↔right association (match). The pairing is server-only — stripped before study. */
export type MatchPair = { left: string; right: string };

/**
 * Type-specific data, discriminated by `cards.type` (validated by the Zod union in the DTO):
 * `open` → null; `quiz` → choices; `type-answer` → shortAnswer; `match` → matchPairs.
 */
export type CardPayload =
  | { choices: CardChoice[] }
  | { shortAnswer: string }
  | { matchPairs: MatchPair[] }
  | null;

/**
 * Optional per-language alternates for a card's question/answer. The PRIMARY language lives in
 * the top-level `question`/`answer` columns (named by `language`); `translations` holds the same
 * card rendered in other languages, so one card can be viewed bilingually (e.g. EN ⇄ PT).
 */
export type CardTranslation = { question: string; answer: string };
export type CardTranslations = Partial<Record<CardLanguage, CardTranslation>>;

export const cards = pgTable(
  'cards',
  {
    id: primaryId(),
    subjectId: text('subject_id')
      .notNull()
      .references(() => subjects.id, { onDelete: 'cascade' }),
    // `open` keeps full backward compatibility; existing rows default to it.
    type: text('type', { enum: CARD_TYPES }).notNull().default('open'),
    // Content language of this card — drives the language badge and the study-language filter.
    language: text('language', { enum: CARD_LANGUAGES }).notNull().default('en'),
    question: text('question').notNull(),
    // For open/quiz/type-answer this is the answer/explanation (Markdown). Match may leave it blank.
    answer: text('answer').notNull(),
    // Null for open cards; type-specific data for the interactive kinds.
    payload: jsonb('payload').$type<CardPayload>(),
    // Optional alternate-language versions of question/answer (primary lives in the columns above).
    translations: jsonb('translations').$type<CardTranslations>(),
    hints: jsonb('hints').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    tags: jsonb('tags').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    createdAt: text('created_at').notNull().$defaultFn(isoNow),
    updatedAt: text('updated_at').notNull().$defaultFn(isoNow),
  },
  (table) => [index('cards_subject_idx').on(table.subjectId)]
);

export const cardProgress = pgTable(
  'card_progress',
  {
    id: primaryId(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    cardId: text('card_id')
      .notNull()
      .references(() => cards.id, { onDelete: 'cascade' }),
    interval: integer('interval').notNull().default(1),
    easeFactor: real('ease_factor').notNull().default(2.5),
    repetitions: integer('repetitions').notNull().default(0),
    nextReviewDate: text('next_review_date').notNull(),
    lastReviewDate: text('last_review_date'),
    status: text('status', {
      enum: ['new', 'learning', 'reviewing', 'mastered'],
    })
      .notNull()
      .default('new'),
    createdAt: text('created_at').notNull().$defaultFn(isoNow),
    updatedAt: text('updated_at').notNull().$defaultFn(isoNow),
  },
  (table) => [
    uniqueIndex('card_progress_user_card_unique').on(table.userId, table.cardId),
    index('card_progress_user_next_idx').on(table.userId, table.nextReviewDate),
  ]
);

export const reviewHistory = pgTable(
  'review_history',
  {
    id: primaryId(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    cardId: text('card_id')
      .notNull()
      .references(() => cards.id, { onDelete: 'cascade' }),
    subjectId: text('subject_id')
      .notNull()
      .references(() => subjects.id, { onDelete: 'cascade' }),
    quality: integer('quality').notNull(),
    reviewedAt: text('reviewed_at').notNull().$defaultFn(isoNow),
    timeSpent: integer('time_spent').notNull(),
    wasHintUsed: boolean('was_hint_used').notNull().default(false),
  },
  (table) => [index('review_history_user_reviewed_idx').on(table.userId, table.reviewedAt)]
);

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Subject = typeof subjects.$inferSelect;
export type NewSubject = typeof subjects.$inferInsert;
export type Card = typeof cards.$inferSelect;
export type NewCard = typeof cards.$inferInsert;
export type CardProgress = typeof cardProgress.$inferSelect;
export type NewCardProgress = typeof cardProgress.$inferInsert;
export type ReviewHistory = typeof reviewHistory.$inferSelect;
export type NewReviewHistory = typeof reviewHistory.$inferInsert;
