/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AuthController_updateMe"];
        trace?: never;
    };
    "/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubjectsController_list"];
        put?: never;
        post: operations["SubjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubjectsController_progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubjectsController_get"];
        put?: never;
        post?: never;
        delete: operations["SubjectsController_remove"];
        options?: never;
        head?: never;
        patch: operations["SubjectsController_update"];
        trace?: never;
    };
    "/v1/subjects/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubjectsController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CardsController_list"];
        put?: never;
        post: operations["CardsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CardsController_get"];
        put?: never;
        post?: never;
        delete: operations["CardsController_remove"];
        options?: never;
        head?: never;
        patch: operations["CardsController_update"];
        trace?: never;
    };
    "/v1/review_queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReviewsController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review_queue/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReviewsController_counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review_queue/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReviewsController_next"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReviewsController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReviewsController_check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quiz_hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReviewsController_eliminate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/weak_cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_weakCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_upcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CatalogController_createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CatalogController_createCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CatalogController_importContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogController_exportContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CatalogController_deleteSubject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/card_reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_list"];
        put?: never;
        post: operations["ReportsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/card_reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ReportsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignupDto: {
            /** Format: email */
            email: string;
            password: string;
            username: string;
        };
        AuthResponseDto: {
            user: {
                id: string;
                email: string;
                username: string;
                language: string;
                theme: string;
                dailyGoal: number;
                createdAt: string;
                updatedAt: string;
            };
            token: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        UserResponseDto: {
            id: string;
            email: string;
            username: string;
            language: string;
            theme: string;
            dailyGoal: number;
            createdAt: string;
            updatedAt: string;
        };
        UpdateMeDto: {
            language?: string;
            /** @enum {string} */
            theme?: "light" | "dark";
            dailyGoal?: number;
        };
        SubjectListDto: {
            /** @constant */
            object: "list";
            url: string;
            has_more: boolean;
            data: {
                id: string;
                userId: string;
                title: string;
                description: string | null;
                color: string | null;
                icon: string | null;
                isPublic: boolean;
                cardCount: number;
                createdAt: string;
                updatedAt: string;
            }[];
        };
        CreateSubjectDto: {
            title: string;
            description?: string;
            color?: string;
            icon?: string;
        };
        SubjectResponseDto: {
            id: string;
            userId: string;
            title: string;
            description: string | null;
            color: string | null;
            icon: string | null;
            isPublic: boolean;
            cardCount: number;
            createdAt: string;
            updatedAt: string;
        };
        SubjectProgressListDto: {
            data: {
                subjectId: string;
                total: number;
                reviewed: number;
                due: number;
            }[];
        };
        UpdateSubjectDto: {
            title?: string;
            description?: string;
            color?: string;
            icon?: string;
        };
        SubjectStatsDto: {
            totalCards: number;
            new: number;
            learning: number;
            reviewing: number;
            mastered: number;
            due: number;
        };
        CardListDto: {
            /** @constant */
            object: "list";
            url: string;
            has_more: boolean;
            data: {
                id: string;
                subjectId: string;
                /** @enum {string} */
                type: "open" | "quiz" | "type-answer" | "match";
                /** @enum {string} */
                language: "en" | "pt";
                question: string;
                answer: string;
                translations?: {
                    en?: {
                        question: string;
                        answer: string;
                    };
                    pt?: {
                        question: string;
                        answer: string;
                    };
                };
                hints: string[];
                tags: string[];
                choices?: {
                    id: string;
                    text: string;
                    isCorrect?: boolean;
                }[];
                shortAnswer?: string;
                matchPairs?: {
                    left: string;
                    right: string;
                }[];
                matchItems?: {
                    lefts: string[];
                    rights: string[];
                };
                createdAt: string;
                updatedAt: string;
            }[];
        };
        CreateCardDto: {
            subjectId: string;
            /**
             * @default open
             * @enum {string}
             */
            type: "open" | "quiz" | "type-answer" | "match";
            question: string;
            /** @enum {string} */
            language?: "en" | "pt";
            translations?: {
                en?: {
                    question: string;
                    answer: string;
                };
                pt?: {
                    question: string;
                    answer: string;
                };
            };
            answer?: string;
            choices?: {
                id: string;
                text: string;
                isCorrect: boolean;
            }[];
            shortAnswer?: string;
            matchPairs?: {
                left: string;
                right: string;
            }[];
            hints?: string[];
            tags?: string[];
        };
        CardResponseDto: {
            id: string;
            subjectId: string;
            /** @enum {string} */
            type: "open" | "quiz" | "type-answer" | "match";
            /** @enum {string} */
            language: "en" | "pt";
            question: string;
            answer: string;
            translations?: {
                en?: {
                    question: string;
                    answer: string;
                };
                pt?: {
                    question: string;
                    answer: string;
                };
            };
            hints: string[];
            tags: string[];
            choices?: {
                id: string;
                text: string;
                isCorrect?: boolean;
            }[];
            shortAnswer?: string;
            matchPairs?: {
                left: string;
                right: string;
            }[];
            matchItems?: {
                lefts: string[];
                rights: string[];
            };
            createdAt: string;
            updatedAt: string;
        };
        UpdateCardDto: {
            question?: string;
            /** @enum {string} */
            language?: "en" | "pt";
            translations?: {
                en?: {
                    question: string;
                    answer: string;
                };
                pt?: {
                    question: string;
                    answer: string;
                };
            };
            answer?: string;
            choices?: {
                id: string;
                text: string;
                isCorrect: boolean;
            }[];
            shortAnswer?: string;
            matchPairs?: {
                left: string;
                right: string;
            }[];
            hints?: string[];
            tags?: string[];
        };
        ReviewQueueResponseDto: {
            due: {
                id: string;
                subjectId: string;
                /** @enum {string} */
                type: "open" | "quiz" | "type-answer" | "match";
                /** @enum {string} */
                language: "en" | "pt";
                question: string;
                answer: string;
                translations?: {
                    en?: {
                        question: string;
                        answer: string;
                    };
                    pt?: {
                        question: string;
                        answer: string;
                    };
                };
                hints: string[];
                tags: string[];
                choices?: {
                    id: string;
                    text: string;
                    isCorrect?: boolean;
                }[];
                shortAnswer?: string;
                matchPairs?: {
                    left: string;
                    right: string;
                }[];
                matchItems?: {
                    lefts: string[];
                    rights: string[];
                };
                createdAt: string;
                updatedAt: string;
            }[];
            new: {
                id: string;
                subjectId: string;
                /** @enum {string} */
                type: "open" | "quiz" | "type-answer" | "match";
                /** @enum {string} */
                language: "en" | "pt";
                question: string;
                answer: string;
                translations?: {
                    en?: {
                        question: string;
                        answer: string;
                    };
                    pt?: {
                        question: string;
                        answer: string;
                    };
                };
                hints: string[];
                tags: string[];
                choices?: {
                    id: string;
                    text: string;
                    isCorrect?: boolean;
                }[];
                shortAnswer?: string;
                matchPairs?: {
                    left: string;
                    right: string;
                }[];
                matchItems?: {
                    lefts: string[];
                    rights: string[];
                };
                createdAt: string;
                updatedAt: string;
            }[];
            total: number;
        };
        ReviewQueueCountsResponseDto: {
            total: number;
            byType: {
                open: number;
                quiz: number;
                "type-answer": number;
                match: number;
            };
            reviewableTotal: number;
            reviewableByType: {
                open: number;
                quiz: number;
                "type-answer": number;
                match: number;
            };
        };
        CreateReviewDto: {
            cardId: string;
            quality?: number;
            response?: {
                /** @constant */
                type: "quiz";
                choiceId: string;
            } | {
                /** @constant */
                type: "type-answer";
                text: string;
            } | {
                /** @constant */
                type: "match";
                pairs: {
                    left: string;
                    right: string;
                }[];
            };
            timeSpent: number;
            wasHintUsed: boolean;
        };
        CheckReviewDto: {
            cardId: string;
            response: {
                /** @constant */
                type: "quiz";
                choiceId: string;
            } | {
                /** @constant */
                type: "type-answer";
                text: string;
            } | {
                /** @constant */
                type: "match";
                pairs: {
                    left: string;
                    right: string;
                }[];
            };
        };
        CheckReviewResponseDto: {
            correct: boolean;
            explanation: string;
            correctChoiceId?: string;
            correctText?: string;
            correctPairs?: {
                left: string;
                right: string;
            }[];
        };
        SubmitReviewResponseDto: {
            progress: {
                id: string;
                userId: string;
                cardId: string;
                interval: number;
                easeFactor: number;
                repetitions: number;
                nextReviewDate: string;
                lastReviewDate: string | null;
                /** @enum {string} */
                status: "new" | "learning" | "reviewing" | "mastered";
                createdAt: string;
                updatedAt: string;
            };
            grade?: {
                correct: boolean;
                explanation: string;
                correctChoiceId?: string;
                correctText?: string;
                correctPairs?: {
                    left: string;
                    right: string;
                }[];
            };
        };
        EliminateChoiceDto: {
            cardId: string;
            /** @default [] */
            eliminatedChoiceIds: string[];
        };
        EliminateChoiceResponseDto: {
            choiceId: string | null;
        };
        DashboardStatsDto: {
            reviewedToday: number;
            dailyGoal: number;
            streak: number;
            accuracy7d: number;
            accuracy30d: number;
            cardsByStatus: {
                new: number;
                learning: number;
                reviewing: number;
                mastered: number;
            };
        };
        WeakCardListDto: {
            /** @constant */
            object: "list";
            url: string;
            has_more: boolean;
            data: {
                id: string;
                question: string;
                easeFactor: number;
                subjectId: string;
                subjectTitle: string;
            }[];
        };
        UpcomingDto: {
            today: number;
            tomorrow: number;
            thisWeek: number;
        };
        CatalogImportDto: {
            subjects?: {
                id?: string;
                title: string;
                description?: string | null;
                color?: string | null;
                icon?: string | null;
            }[];
            cards?: {
                id?: string;
                subjectId: string;
                /** @enum {string} */
                type?: "open" | "quiz" | "type-answer" | "match";
                /** @enum {string} */
                language?: "en" | "pt";
                translations?: {
                    en?: {
                        question: string;
                        answer: string;
                    };
                    pt?: {
                        question: string;
                        answer: string;
                    };
                };
                question: string;
                answer?: string;
                choices?: {
                    id: string;
                    text: string;
                    isCorrect: boolean;
                }[];
                shortAnswer?: string;
                matchPairs?: {
                    left: string;
                    right: string;
                }[];
                hints?: string[];
                tags?: string[];
            }[];
        };
        ImportResultDto: {
            subjects: {
                created: number;
                updated: number;
            };
            cards: {
                created: number;
                updated: number;
            };
            errors: {
                index: number;
                id?: string;
                error: string;
            }[];
        };
        CatalogExportDto: {
            subjects: {
                id: string;
                title: string;
                description?: string | null;
                color?: string | null;
                icon?: string | null;
            }[];
            cards: {
                id: string;
                subjectId: string;
                /** @enum {string} */
                type: "open" | "quiz" | "type-answer" | "match";
                /** @enum {string} */
                language: "en" | "pt";
                question: string;
                answer: string;
                translations?: {
                    en?: {
                        question: string;
                        answer: string;
                    };
                    pt?: {
                        question: string;
                        answer: string;
                    };
                };
                hints: string[];
                tags: string[];
                choices?: {
                    id: string;
                    text: string;
                    isCorrect?: boolean;
                }[];
                shortAnswer?: string;
                matchPairs?: {
                    left: string;
                    right: string;
                }[];
                matchItems?: {
                    lefts: string[];
                    rights: string[];
                };
                createdAt: string;
                updatedAt: string;
            }[];
        };
        ReportListDto: {
            /** @constant */
            object: "list";
            url: string;
            has_more: boolean;
            data: {
                id: string;
                cardId: string;
                subjectId: string;
                /** @enum {string} */
                reason: "incorrect" | "improvement";
                message: string | null;
                createdAt: string;
                updatedAt: string;
            }[];
        };
        CreateReportDto: {
            cardId: string;
            /** @enum {string} */
            reason: "incorrect" | "improvement";
            message?: string;
        };
        ReportResponseDto: {
            id: string;
            cardId: string;
            subjectId: string;
            /** @enum {string} */
            reason: "incorrect" | "improvement";
            message: string | null;
            createdAt: string;
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    SubjectsController_list: {
        parameters: {
            query?: {
                limit?: number;
                starting_after?: string;
                ending_before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectListDto"];
                };
            };
        };
    };
    SubjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponseDto"];
                };
            };
        };
    };
    SubjectsController_progress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectProgressListDto"];
                };
            };
        };
    };
    SubjectsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponseDto"];
                };
            };
        };
    };
    SubjectsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponseDto"];
                };
            };
        };
    };
    SubjectsController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectStatsDto"];
                };
            };
        };
    };
    CardsController_list: {
        parameters: {
            query: {
                limit?: number;
                starting_after?: string;
                ending_before?: string;
                subject: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListDto"];
                };
            };
        };
    };
    CardsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponseDto"];
                };
            };
        };
    };
    CardsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponseDto"];
                };
            };
        };
    };
    CardsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCardDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponseDto"];
                };
            };
        };
    };
    ReviewsController_queue: {
        parameters: {
            query?: {
                subject?: string;
                type?: "open" | "quiz" | "type-answer" | "match";
                ahead?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueResponseDto"];
                };
            };
        };
    };
    ReviewsController_counts: {
        parameters: {
            query?: {
                subject?: string;
                type?: "open" | "quiz" | "type-answer" | "match";
                ahead?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueCountsResponseDto"];
                };
            };
        };
    };
    ReviewsController_next: {
        parameters: {
            query?: {
                subject?: string;
                type?: "open" | "quiz" | "type-answer" | "match";
                ahead?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponseDto"];
                };
            };
        };
    };
    ReviewsController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitReviewResponseDto"];
                };
            };
        };
    };
    ReviewsController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckReviewResponseDto"];
                };
            };
        };
    };
    ReviewsController_eliminate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EliminateChoiceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EliminateChoiceResponseDto"];
                };
            };
        };
    };
    DashboardController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsDto"];
                };
            };
        };
    };
    DashboardController_weakCards: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeakCardListDto"];
                };
            };
        };
    };
    DashboardController_upcoming: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingDto"];
                };
            };
        };
    };
    CatalogController_createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponseDto"];
                };
            };
        };
    };
    CatalogController_createCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponseDto"];
                };
            };
        };
    };
    CatalogController_importContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogImportDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultDto"];
                };
            };
        };
    };
    CatalogController_exportContent: {
        parameters: {
            query?: {
                subject?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogExportDto"];
                };
            };
        };
    };
    CatalogController_deleteSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_list: {
        parameters: {
            query?: {
                limit?: number;
                starting_after?: string;
                ending_before?: string;
                subject?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListDto"];
                };
            };
        };
    };
    ReportsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponseDto"];
                };
            };
        };
    };
    ReportsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
